### ISSUE TITLE
Add Celery instrumentation

### ISSUE THREAD

**Issue by cschneid** [scoutapp/scout_apm_python#6]
Add support for Celery background job instrumentation.

The start of a TODO List:

* [ ] Startup & setup hooks
* [ ] Instrumentation (queue throughput, depth, job details)
* [ ] Documentation
* [ ] Core-agent support for background Jobs

**Comment by cschneid** [comment]
An initial bit of code for celery support is released in scout_apm 1.1.3.

```
import scout_apm.celery
from celery import Celery

app = Celery('tasks', backend='redis://localhost', broker='redis://localhost')
scout_apm.celery.install()
```

There are still some other features to add:

- Capturing Queue Name #34
- Capturing Time in Queue #35
- Possibly support for more complex job structures (Chains, Chords, etc). #36
